- hosts: all
  become: yes
  tasks:
    - name: Установка Apache2
      dnf:
 name: httpd
        state: present
      become: true
    - name: Включение httpd
      service:
 name: httpd
        state: started
        enabled: yes
    - name: Открытие порта в firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
