---
- hosts: all
  become: yes
  vars:
    surname: "Кульбезеков"  # Замените на вашу фамилию
    variant: "1"       # Замените на ваш вариант
    group: "С1-21"  # Замените на вашу группу

  tasks:
    - name: Install Apache
      dnf:
 name: httpd
        state: present

    - name: Start and enable Apache
      service:
 name: httpd
        state: started
        enabled: yes

    - name: Install MySQL (MariaDB)
      dnf:
 name: mariadb-server
        state: present

    - name: Start and enable MySQL
      service:
 name: mariadb
        state: started
        enabled: yes

    - name: Install PHP
      dnf:
 name: php
        state: present
    - name: Install PHP MySQL extension
      dnf:
        name: php-mysqlnd
        state: present

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Set permissions for WordPress directory
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes

    - name: Create a custom wp-config.php with personal info
      copy:
        content: |
          <?php
          define('DB_NAME', 'wordpress');
          define('DB_USER', 'root');
          define('DB_PASSWORD', '');
          define('DB_HOST', 'localhost');
          define('WP_DEBUG', true);
          echo "Фамилия: {{ surname }}, Вариант: {{ variant }}, Группа: {{ group }}";
          ?>
        dest: /var/www/html/wordpress/wp-config.php
        owner: apache
        group: apache
        mode: '0644'

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
